version: 1.0.{build}

build:
  project: audio_arranger

environment:
  matrix:
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install pyinstaller"

build_script:
  - "pyinstaller --onefile --add-binary 'C:\\Windows\\System32\\*.dll;.' audio.py"

test_script:
  - "dir dist"
  - "dir build\\audio"
  - "echo %CD%"
  - "echo %PATH%"

artifacts:
  - path: "dist\\audio.exe"
    name: executable
